name: build - linux

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt install build-essential nasm curl make

      - name: Fetch and install toolchain
        run: |
          curl https://github.com/lux-operating-system/toolchain-x86_64/releases/download/github-runners/toolchain-linux-x86_64.tar.xz -o toolchain-linux-x86_64.tar.xz
          tar -xvJf toolchain-linux-x86_64.tar.xz
          mv toolchain $HOME/work/toolchain
          mv host $HOME/work/host
          echo "$HOME/work/toolchain/bin" >> $GITHUB_PATH

      - name: Verify toolchain is executable
        run: x86_64-lux-gcc -v

      - name: Build kernel
        run: make
    
      - name: Clean up artifacts
        run: |
          rm -rf toolchain-linux-x86_64.tar.xz $HOME/work/toolchain $HOME/work/host
          make clean
